export const userId = "1";

export const fakeUser = {
    _id: "1",
    firstName: "Jaydee",
    lastName: "Ramos",
    email: "jaydeeramos@gmail.com",
    userProfileImage:
        "https://res.cloudinary.com/dkkcgnkep/image/upload/v1684493395/aremynet63dcu940seyz.jpg",
    created_at: "",
    updated_at: "",
};

export const fakeMessagesSaul = [
    {
        _id: "1",
        messageType: "text",
        content: "Saul, I need your help.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T04:58:21Z",
        updated_at: "",
    },
    {
        _id: "2",
        messageType: "text",
        content: "Sure thing, Denzel. What can I do for you?",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T05:03:21Z",
        updated_at: "",
    },
    {
        _id: "3",
        messageType: "text",
        content:
            "I got into a bit of trouble with the law. I need someone to represent me.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T05:08:21Z",
        updated_at: "",
    },
    {
        _id: "4",
        messageType: "text",
        content: "I see. What kind of trouble are we talking about?",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T05:13:21Z",
        updated_at: "",
    },
    {
        _id: "5",
        messageType: "text",
        content:
            "I got caught with some drugs in my car. The cops searched me without a warrant.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T05:18:21Z",
        updated_at: "",
    },
    {
        _id: "6",
        messageType: "text",
        content:
            "Hmm, that's not good. But don't worry, I can definitely help you out with that.",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T05:23:21Z",
        updated_at: "",
    },
    {
        _id: "7",
        messageType: "text",
        content: "What's your fee for representing me?",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T05:28:21Z",
        updated_at: "",
    },
    {
        _id: "8",
        messageType: "text",
        content:
            "It depends on the complexity of the case. We can discuss it in more detail when we meet.",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T05:33:21Z",
        updated_at: "",
    },
    {
        _id: "9",
        messageType: "text",
        content: "Okay, that sounds fair. When can we meet?",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T05:38:21Z",
        updated_at: "",
    },
    {
        _id: "10",
        messageType: "text",
        content: "How about tomorrow at 3pm? We can meet at my office.",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T05:43:21Z",
        updated_at: "",
    },
    {
        _id: "11",
        messageType: "text",
        content: "Alright, I'll be there. Can you send me the address?",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T05:48:21Z",
        updated_at: "",
    },
    {
        _id: "12",
        messageType: "text",
        content:
            "Of course, I'll send it to you now. Is there anything else you need help with?",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T05:53:21Z",
        updated_at: "",
    },
    {
        _id: "13",
        messageType: "text",
        content: "No, that's all for now. Thank you for your help, Saul.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T05:58:21Z",
        updated_at: "",
    },
    {
        _id: "14",
        messageType: "text",
        content: "No problem, Denzel. I'll see you tomorrow.",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:03:21Z",
        updated_at: "",
    },
    {
        _id: "15",
        messageType: "text",
        content:
            "Hey, Saul. I forgot to ask, what should I bring to our meeting?",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T06:08:21Z",
        updated_at: "",
    },
    {
        _id: "16",
        messageType: "text",
        content:
            "Just bring any relevant documents related to your case, and be prepared to answer some questions.",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:13:21Z",
        updated_at: "",
    },
    {
        _id: "17",
        messageType: "text",
        content: "Got it, thanks for letting me know.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T06:18:21Z",
        updated_at: "",
    },
    {
        _id: "18",
        messageType: "text",
        content: "No problem. See you tomorrow, Denzel.",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:23:21Z",
        updated_at: "",
    },
    {
        _id: "19",
        messageType: "text",
        content: "See you tomorrow, Saul.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T06:28:21Z",
        updated_at: "",
    },
    {
        _id: "20",
        messageType: "text",
        content: "Goodbye, Denzel.",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "21",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787150/ugbsrtmlf4wdgv7cnat6.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "22",
        messageType: "text",
        content: "random text",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "23",
        messageType: "text",
        content: "random text 2",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "10",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "24",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787150/ugbsrtmlf4wdgv7cnat6.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "25",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683522756/gkbssjdzgynfpfixe6ss.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "26",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787221/sfsbboxts77ear5cc4gu.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "27",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683365247/pkjr7u2eyndcfx41jsvq.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "28",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "29",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787150/ugbsrtmlf4wdgv7cnat6.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "30",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683522756/gkbssjdzgynfpfixe6ss.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "31",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787221/sfsbboxts77ear5cc4gu.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "32",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683365247/pkjr7u2eyndcfx41jsvq.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "33",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "34",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787150/ugbsrtmlf4wdgv7cnat6.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "35",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683522756/gkbssjdzgynfpfixe6ss.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "36",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787221/sfsbboxts77ear5cc4gu.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "37",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683365247/pkjr7u2eyndcfx41jsvq.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "38",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "39",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "40",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787150/ugbsrtmlf4wdgv7cnat6.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "41",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683522756/gkbssjdzgynfpfixe6ss.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "42",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787221/sfsbboxts77ear5cc4gu.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "43",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683365247/pkjr7u2eyndcfx41jsvq.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "44",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "45",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "46",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787150/ugbsrtmlf4wdgv7cnat6.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "47",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683522756/gkbssjdzgynfpfixe6ss.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "48",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787221/sfsbboxts77ear5cc4gu.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "49",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683365247/pkjr7u2eyndcfx41jsvq.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
    {
        _id: "50",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
        senderId: "10",
        senderName: "Saul Goodman",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
];

export const fakeMessagesKim = [
    {
        _id: "1",
        messageType: "text",
        content: "Hi Kim, I hope you're doing well!",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "11",
        status: "seen",
        created_at: "2023-05-12T08:00:00Z",
        updated_at: "",
    },
    {
        _id: "2",
        messageType: "text",
        content: "Hi Denzel, I'm doing well, thank you. How can I help you?",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T08:05:00Z",
        updated_at: "",
    },
    {
        _id: "3",
        messageType: "text",
        content: "I need some legal advice on a personal matter.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "11",
        status: "seen",
        created_at: "2023-05-12T08:10:00Z",
        updated_at: "",
    },
    {
        _id: "4",
        messageType: "text",
        content: "Sure, I'd be happy to help. What's the issue?",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T08:15:00Z",
        updated_at: "",
    },
    {
        _id: "5",
        messageType: "text",
        content:
            "I was in a car accident last week, and I'm not sure what to do next.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "11",
        status: "seen",
        created_at: "2023-05-12T08:20:00Z",
        updated_at: "",
    },
    {
        _id: "6",
        messageType: "text",
        content: "Are you injured? Have you seen a doctor?",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T08:25:00Z",
        updated_at: "",
    },
    {
        _id: "7",
        messageType: "text",
        content:
            "I'm okay, just a few bumps and bruises. I haven't seen a doctor yet.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "11",
        status: "seen",
        created_at: "2023-05-12T08:30:00Z",
        updated_at: "",
    },
    {
        _id: "8",
        messageType: "text",
        content:
            "You should see a doctor as soon as possible. It's important to document any injuries, even if they seem minor.",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T08:35:00Z",
        updated_at: "",
    },
    {
        _id: "9",
        messageType: "text",
        content:
            "Thanks, Kim. I'll make an appointment today. But what about the other driver? They were at fault, and I'm not sure what my rights are.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "11",
        status: "seen",
        created_at: "2023-05-12T08:45:00Z",
        updated_at: "",
    },
    {
        _id: "10",
        messageType: "text",
        content:
            "You should contact a personal injury lawyer. They can help you navigate the legal process and ensure that you receive the compensation you deserve.",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T08:50:00Z",
        updated_at: "",
    },
    {
        _id: "11",
        messageType: "text",
        content: "Okay, do you know any good lawyers in the area?",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "11",
        status: "seen",
        created_at: "2023-05-12T08:55:00Z",
        updated_at: "",
    },
    {
        _id: "12",
        messageType: "text",
        content:
            "Yes, I can recommend a few. I'll send you their contact information.",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T09:00:00Z",
        updated_at: "",
    },
    {
        _id: "13",
        messageType: "text",
        content: "Thank you so much, Kim. You've been a huge help.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "11",
        status: "seen",
        created_at: "2023-05-12T09:05:00Z",
        updated_at: "",
    },
    {
        _id: "14",
        messageType: "text",
        content:
            "No problem, Denzel. I'm glad I could assist you. Let me know if you need anything else.",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T09:10:00Z",
        updated_at: "",
    },
    {
        _id: "15",
        messageType: "text",
        content: "Will do. Thanks again, Kim!",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "11",
        status: "seen",
        created_at: "2023-05-12T09:15:00Z",
        updated_at: "",
    },
    {
        _id: "16",
        messageType: "text",
        content: "You're welcome, Denzel. Take care!",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T09:20:00Z",
        updated_at: "",
    },
    {
        _id: "17",
        messageType: "text",
        content: "You too, Kim.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "11",
        status: "seen",
        created_at: "2023-05-12T09:25:00Z",
        updated_at: "",
    },
    {
        _id: "18",
        messageType: "text",
        content: "Bye for now!",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T09:30:00Z",
        updated_at: "",
    },
    {
        _id: "19",
        messageType: "text",
        content: "Bye!",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "11",
        status: "seen",
        created_at: "2023-05-12T09:35:00Z",
        updated_at: "",
    },
    {
        _id: "20",
        messageType: "text",
        content: "Take care!",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T09:40:00Z",
        updated_at: "",
    },
    {
        _id: "21",
        messageType: "image",
        content:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
        senderId: "11",
        senderName: "Kim Wexler",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T06:33:21Z",
        updated_at: "",
    },
];

export const fakeMessagesLalo = [
    {
        _id: "1",
        messageType: "text",
        content: "Hey Lalo, can we talk?",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "12",
        status: "seen",
        created_at: "2023-05-12T10:00:00Z",
        updated_at: "",
    },
    {
        _id: "2",
        messageType: "text",
        content: "Sure, Denzel. What's up?",
        senderId: "12",
        senderName: "Lalo Salamanca",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T10:05:00Z",
        updated_at: "",
    },
    {
        _id: "3",
        messageType: "text",
        content:
            "I need your help. I have some trouble with the police and I need a good lawyer.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "12",
        status: "seen",
        created_at: "2023-05-12T10:10:00Z",
        updated_at: "",
    },
    {
        _id: "4",
        messageType: "text",
        content:
            "I see. You've come to the right place. I know just the lawyer for you.",
        senderId: "12",
        senderName: "Lalo Salamanca",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T10:15:00Z",
        updated_at: "",
    },
    {
        _id: "5",
        messageType: "text",
        content: "Thank you, Lalo. I really appreciate it.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "12",
        status: "seen",
        created_at: "2023-05-12T10:20:00Z",
        updated_at: "",
    },
    {
        _id: "6",
        messageType: "text",
        content:
            "No problem, Denzel. I'll take care of everything. Do you have any other questions?",
        senderId: "12",
        senderName: "Lalo Salamanca",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T10:25:00Z",
        updated_at: "",
    },
    {
        _id: "7",
        messageType: "text",
        content: "Yes, how long do you think this will take?",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "12",
        status: "seen",
        created_at: "2023-05-12T10:30:00Z",
        updated_at: "",
    },
    {
        _id: "8",
        messageType: "text",
        content:
            "It depends on the case, but I can assure you that my lawyer will do everything possible to get you out of trouble as soon as possible.",
        senderId: "12",
        senderName: "Lalo Salamanca",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T10:35:00Z",
        updated_at: "",
    },
    {
        _id: "9",
        messageType: "text",
        content: "Thanks, Lalo. You're a true friend.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "12",
        status: "seen",
        created_at: "2023-05-12T10:45:00Z",
        updated_at: "",
    },
    {
        _id: "10",
        messageType: "text",
        content:
            "You're welcome, Denzel. That's what friends are for. Let me know if you need anything else.",
        senderId: "12",
        senderName: "Lalo Salamanca",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T10:50:00Z",
        updated_at: "",
    },
    {
        _id: "11",
        messageType: "text",
        content:
            "Actually, there is something else. I'm worried that someone might be watching me. Do you know anyone who can help me with this?",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "12",
        status: "seen",
        created_at: "2023-05-12T10:55:00Z",
        updated_at: "",
    },
    {
        _id: "12",
        messageType: "text",
        content:
            "I see. You're right to be concerned. I know just the person who can help you. Let me make a few calls and I'll get back to you soon.",
        senderId: "12",
        senderName: "Lalo Salamanca",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T11:00:00Z",
        updated_at: "",
    },
    {
        _id: "13",
        messageType: "text",
        content:
            "Thanks, Lalo. I really appreciate it. I'll be waiting for your call.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "12",
        status: "seen",
        created_at: "2023-05-12T11:05:00Z",
        updated_at: "",
    },
    {
        _id: "14",
        messageType: "text",
        content:
            "No problem, Denzel. I'll get back to you as soon as I can. Stay safe.",
        senderId: "12",
        senderName: "Lalo Salamanca",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T11:10:00Z",
        updated_at: "",
    },
    {
        _id: "15",
        messageType: "text",
        content: "Will do, Lalo. Thanks again.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "12",
        status: "seen",
        created_at: "2023-05-12T11:15:00Z",
        updated_at: "",
    },
    {
        _id: "16",
        messageType: "text",
        content: "Anytime, Denzel. Take care.",
        senderId: "12",
        senderName: "Lalo Salamanca",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T11:20:00Z",
        updated_at: "",
    },
    {
        _id: "17",
        messageType: "text",
        content: "Great! I'll be in touch soon.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "12",
        status: "seen",
        created_at: "2023-05-12T11:30:00Z",
        updated_at: "",
    },
    {
        _id: "18",
        messageType: "text",
        content: "Sounds good, Denzel. Take care.",
        senderId: "12",
        senderName: "Lalo Salamanca",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T11:35:00Z",
        updated_at: "",
    },
    {
        _id: "19",
        messageType: "text",
        content: "Thank you, Lalo. You too.",
        senderId: "1",
        senderName: "Denzel Ramos",
        receiverId: "12",
        status: "seen",
        created_at: "2023-05-12T11:40:00Z",
        updated_at: "",
    },
    {
        _id: "20",
        messageType: "text",
        content: "Bye!",
        senderId: "12",
        senderName: "Lalo Salamanca",
        receiverId: "1",
        status: "seen",
        created_at: "2023-05-12T11:45:00Z",
        updated_at: "",
    },
];

export const fakeActiveUsers = [
    {
        socketId: "1",
        userId: "10",
        userInfo: {
            _id: "10",
            firstName: "Saul",
            lastName: "Goodman",
            email: "saulgoodman@gmail.com",
            userProfileImage:
                "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
            created_at: "",
            updated_at: "",
        },
    },
    {
        socketId: "2",
        userId: "11",
        userInfo: {
            _id: "11",
            firstName: "Kim",
            lastName: "Wexler",
            email: "kimwexler@gmail.com",
            userProfileImage:
                "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683365247/pkjr7u2eyndcfx41jsvq.png",
            created_at: "",
            updated_at: "",
        },
    },
];

export const fakeFriends = [
    {
        friendInfo: {
            _id: "10",
            firstName: "Saul",
            lastName: "Goodman",
            email: "saulgoodman@gmail.com",
            userProfileImage:
                "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
            created_at: "",
            updated_at: "",
        },
        latestMessage: {
            _id: "5",
            messageType: "text",
            content: "My name is Saul. Saul Goodman at your service.",
            senderId: "10",
            senderName: "Saul Goodman",
            receiverId: "1",
            status: "seen",
            created_at: "2023-05-12T04:58:21Z",
            updated_at: "",
        },
    },
    {
        friendInfo: {
            _id: "11",
            firstName: "Kim",
            lastName: "Wexler",
            email: "kimwexler@gmail.com",
            userProfileImage:
                "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683365247/pkjr7u2eyndcfx41jsvq.png",
            created_at: "",
            updated_at: "",
        },
        latestMessage: {
            _id: "5",
            messageType: "text",
            content: "My name is Kim. Kim Wexler at your service.",
            senderId: "11",
            senderName: "Kim Wexler",
            receiverId: "1",
            status: "delivered",
            created_at: "2023-05-12T04:18:21Z",
            updated_at: "",
        },
    },
    {
        friendInfo: {
            _id: "12",
            firstName: "Lalo",
            lastName: "Salamanca",
            email: "lalosalamanca@gmail.com",
            userProfileImage:
                "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683522756/gkbssjdzgynfpfixe6ss.png",
            created_at: "",
            updated_at: "",
        },
        latestMessage: {
            _id: "5",
            messageType: "text",
            content: "Werner Zeiglerrrrr",
            senderId: "12",
            senderName: "Lalo Salamanca",
            receiverId: "1",
            status: "seen",
            created_at: "2023-05-12T02:18:21Z",
            updated_at: "",
        },
    },
    {
        friendInfo: {
            _id: "13",
            firstName: "Walter",
            lastName: "White",
            email: "walterwhite@gmail.com",
            userProfileImage:
                "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787150/ugbsrtmlf4wdgv7cnat6.png",
            created_at: "",
            updated_at: "",
        },
        latestMessage: {
            _id: "5",
            messageType: "text",
            content: "Now, say my name",
            senderId: "13",
            senderName: "Walter White",
            receiverId: "1",
            status: "delivered",
            created_at: "2023-05-08T05:18:21Z",
            updated_at: "",
        },
    },
    {
        friendInfo: {
            _id: "14",
            firstName: "Jesse",
            lastName: "Pinkman",
            email: "jessepinkman@gmail.com",
            userProfileImage:
                "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787221/sfsbboxts77ear5cc4gu.png",
            created_at: "",
            updated_at: "",
        },
        latestMessage: {
            _id: "5",
            messageType: "text",
            content: "Do you know what is science?",
            senderId: "1",
            senderName: "Walter White",
            receiverId: "14",
            status: "delivered",
            created_at: "2023-03-29T05:18:21Z",
            updated_at: "",
        },
    },
];

export const fakeFriendRequestSent = [
    {
        _id: "10",
        firstName: "Saul",
        lastName: "Goodman",
        email: "saulgoodman@gmail.com",
        userProfileImage:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683349951/nxbrqywajxpgm9jzblwz.png",
        created_at: "",
        updated_at: "",
    },
    {
        _id: "11",
        firstName: "Kim",
        lastName: "Wexler",
        email: "kimwexler@gmail.com",
        userProfileImage:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683365247/pkjr7u2eyndcfx41jsvq.png",
        created_at: "",
        updated_at: "",
    },
    {
        _id: "12",
        firstName: "Lalo",
        lastName: "Salamanca",
        email: "lalosalamanca@gmail.com",
        userProfileImage:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683522756/gkbssjdzgynfpfixe6ss.png",
        created_at: "",
        updated_at: "",
    },
    {
        _id: "13",
        firstName: "Walter",
        lastName: "White",
        email: "walterwhite@gmail.com",
        userProfileImage:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787150/ugbsrtmlf4wdgv7cnat6.png",
        created_at: "",
        updated_at: "",
    },
];

export const fakeFriendRequestReceived = [
    {
        _id: "11",
        firstName: "Kim",
        lastName: "Wexler",
        email: "kimwexler@gmail.com",
        userProfileImage:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683365247/pkjr7u2eyndcfx41jsvq.png",
        created_at: "",
        updated_at: "",
    },
    {
        _id: "12",
        firstName: "Lalo",
        lastName: "Salamanca",
        email: "lalosalamanca@gmail.com",
        userProfileImage:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683522756/gkbssjdzgynfpfixe6ss.png",
        created_at: "",
        updated_at: "",
    },
    {
        _id: "13",
        firstName: "Walter",
        lastName: "White",
        email: "walterwhite@gmail.com",
        userProfileImage:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787150/ugbsrtmlf4wdgv7cnat6.png",
        created_at: "",
        updated_at: "",
    },
    {
        _id: "14",
        firstName: "Jesse",
        lastName: "Pinkman",
        email: "jessepinkman@gmail.com",
        userProfileImage:
            "https://res.cloudinary.com/dkkcgnkep/image/upload/v1683787221/sfsbboxts77ear5cc4gu.png",
        created_at: "",
        updated_at: "",
    },
];
